#!/usr/bin/env python3

from enum import Enum, unique, auto

@unique
class AddrMode(Enum):
	Implied = auto()
	Accumulator = auto()
	Immediate = auto()
	ZeroPage = auto()
	ZeroPageX = auto()
	ZeroPageY = auto()
	Absolute = auto()
	AbsoluteX = auto()
	AbsoluteY = auto()
	AbsIndirect = auto()
	IndirectX = auto()
	IndirectY = auto()
	Relative = auto()

modes = {
	AddrMode.Implied		: (0, ""),
	AddrMode.Accumulator	: (0, "A"),
	AddrMode.Immediate		: (1, "#{}"),
	AddrMode.ZeroPageX		: (1, "{},X"),
	AddrMode.ZeroPageY		: (1, "{},Y"),
	AddrMode.Absolute		: (2, "{}"),
	AddrMode.AbsoluteX		: (2, "{},X"),
	AddrMode.AbsoluteY		: (2, "{},Y"),
	AddrMode.AbsIndirect	: (2, "({})"),
	AddrMode.IndirectX		: (2, "({},X)"),
	AddrMode.IndirectY		: (2, "({}),Y"),
	AddrMode.Relative		: (1, "{}")
	}

menumonics = [
	("BRK",   AddrMode.Implied),
	("ORA",   AddrMode.IndirectX),
	("JAM",   AddrMode.Implied),
	("SLO",   AddrMode.IndirectX),
	("NOOP",  AddrMode.ZeroPage),
	("ORA",   AddrMode.ZeroPage),
	("ASL",   AddrMode.ZeroPage),
	("SLO",   AddrMode.ZeroPage),
	("PHP",   AddrMode.Implied),
	("ORA",   AddrMode.Immediate),
	("ASL",   AddrMode.Accumulator),
	("ANC",   AddrMode.Immediate),
	("NOOP",  AddrMode.Absolute),
	("ORA",   AddrMode.Absolute),
	("ASL",   AddrMode.Absolute),
	("SLO",   AddrMode.Absolute),
	("BPL",   AddrMode.Relative),
	("ORA",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("SLO",   AddrMode.IndirectY),
	("NOOP",  AddrMode.ZeroPageX),
	("ORA",   AddrMode.ZeroPageX),
	("ASL",   AddrMode.ZeroPageX),
	("SLO",   AddrMode.ZeroPageX),
	("CLC",   AddrMode.Implied),
	("ORA",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.Implied),
	("SLO",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.AbsoluteX),
	("ORA",   AddrMode.AbsoluteX),
	("ASL",   AddrMode.AbsoluteX),
	("SLO",   AddrMode.AbsoluteX),
	("JSR",   AddrMode.Absolute),
	("AND",   AddrMode.IndirectX),
	("JAM",   AddrMode.Implied),
	("RLA",   AddrMode.IndirectX),
	("BIT",   AddrMode.ZeroPage),
	("AND",   AddrMode.ZeroPage),
	("ROL",   AddrMode.ZeroPage),
	("RLA",   AddrMode.ZeroPage),
	("PLP",   AddrMode.Implied),
	("AND",   AddrMode.Immediate),
	("ROL",   AddrMode.Accumulator),
	("ANC",   AddrMode.Immediate),
	("BIT",   AddrMode.Absolute),
	("AND",   AddrMode.Absolute),
	("ROL",   AddrMode.Absolute),
	("RLA",   AddrMode.Absolute),
	("BMI",   AddrMode.Relative),
	("AND",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("RLA",   AddrMode.IndirectY),
	("NOOP",  AddrMode.ZeroPageX),
	("AND",   AddrMode.ZeroPageX),
	("ROL",   AddrMode.ZeroPageX),
	("RLA",   AddrMode.ZeroPageX),
	("SEC",   AddrMode.Implied),
	("AND",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.Implied),
	("RLA",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.AbsoluteX),
	("AND",   AddrMode.AbsoluteX),
	("ROL",   AddrMode.AbsoluteX),
	("RLA",   AddrMode.AbsoluteX),
	("RTI",   AddrMode.Implied),
	("EOR",   AddrMode.IndirectX),
	("JAM",   AddrMode.Implied),
	("SRE",   AddrMode.IndirectX),
	("NOOP",  AddrMode.ZeroPage),
	("EOR",   AddrMode.ZeroPage),
	("LSR",   AddrMode.ZeroPage),
	("SRE",   AddrMode.ZeroPage),
	("PHA",   AddrMode.Implied),
	("EOR",   AddrMode.Immediate),
	("LSR",   AddrMode.Accumulator),
	("ASR",   AddrMode.Immediate),
	("JMP",   AddrMode.Absolute),
	("EOR",   AddrMode.Absolute),
	("LSR",   AddrMode.Absolute),
	("SRE",   AddrMode.Absolute),
	("BVC",   AddrMode.Relative),
	("EOR",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("SRE",   AddrMode.IndirectY),
	("NOOP",  AddrMode.ZeroPageX),
	("EOR",   AddrMode.ZeroPageX),
	("LSR",   AddrMode.ZeroPageX),
	("SRE",   AddrMode.ZeroPageX),
	("CLI",   AddrMode.Implied),
	("EOR",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.Implied),
	("SRE",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.AbsoluteX),
	("EOR",   AddrMode.AbsoluteX),
	("LSR",   AddrMode.AbsoluteX),
	("SRE",   AddrMode.AbsoluteX),
	("RTS",   AddrMode.Implied),
	("ADC",   AddrMode.IndirectX),
	("JAM",   AddrMode.Implied),
	("RRA",   AddrMode.IndirectX),
	("NOOP",  AddrMode.ZeroPage),
	("ADC",   AddrMode.ZeroPage),
	("ROR",   AddrMode.ZeroPage),
	("RRA",   AddrMode.ZeroPage),
	("PLA",   AddrMode.Implied),
	("ADC",   AddrMode.Immediate),
	("ROR",   AddrMode.Accumulator),
	("ARR",   AddrMode.Immediate),
	("JMP",   AddrMode.AbsIndirect),
	("ADC",   AddrMode.Absolute),
	("ROR",   AddrMode.Absolute),
	("RRA",   AddrMode.Absolute),
	("BVS",   AddrMode.Relative),
	("ADC",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("RRA",   AddrMode.IndirectY),
	("NOOP",  AddrMode.ZeroPageX),
	("ADC",   AddrMode.ZeroPageX),
	("ROR",   AddrMode.ZeroPageX),
	("RRA",   AddrMode.ZeroPageX),
	("SEI",   AddrMode.Implied),
	("ADC",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.Implied),
	("RRA",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.AbsoluteX),
	("ADC",   AddrMode.AbsoluteX),
	("ROR",   AddrMode.AbsoluteX),
	("RRA",   AddrMode.AbsoluteX),
	("NOOP",  AddrMode.Immediate),
	("STA",   AddrMode.IndirectX),
	("NOOP",  AddrMode.Immediate),
	("SAX",   AddrMode.IndirectX),
	("STY",   AddrMode.ZeroPage),
	("STA",   AddrMode.ZeroPage),
	("STX",   AddrMode.ZeroPage),
	("SAX",   AddrMode.ZeroPage),
	("DEY",   AddrMode.Implied),
	("NOOP",  AddrMode.Immediate),
	("TXA",   AddrMode.Implied),
	("ANE",   AddrMode.Immediate),
	("STY",   AddrMode.Absolute),
	("STA",   AddrMode.Absolute),
	("STX",   AddrMode.Absolute),
	("SAX",   AddrMode.Absolute),
	("BCC",   AddrMode.Relative),
	("STA",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("SHA",   AddrMode.IndirectY),
	("STY",   AddrMode.ZeroPageX),
	("STA",   AddrMode.ZeroPageX),
	("STX",   AddrMode.ZeroPageY),
	("SAX",   AddrMode.ZeroPageY),
	("TYA",   AddrMode.Implied),
	("STA",   AddrMode.AbsoluteY),
	("TXS",   AddrMode.Implied),
	("SHS",   AddrMode.AbsoluteY),
	("SHY",   AddrMode.AbsoluteX),
	("STA",   AddrMode.AbsoluteX),
	("SHX",   AddrMode.AbsoluteY),
	("SHA",   AddrMode.AbsoluteY),
	("LDY",   AddrMode.Immediate),
	("LDA",   AddrMode.IndirectX),
	("LDX",   AddrMode.Immediate),
	("LAX",   AddrMode.IndirectX),
	("LDY",   AddrMode.ZeroPage),
	("LDA",   AddrMode.ZeroPage),
	("LDX",   AddrMode.ZeroPage),
	("LAX",   AddrMode.ZeroPage),
	("TAY",   AddrMode.Implied),
	("LDA",   AddrMode.Immediate),
	("TAX",   AddrMode.Implied),
	("LXA",   AddrMode.Immediate),
	("LDY",   AddrMode.Absolute),
	("LDA",   AddrMode.Absolute),
	("LDX",   AddrMode.Absolute),
	("LAX",   AddrMode.Absolute),
	("BCS",   AddrMode.Relative),
	("LDA",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("LAX",   AddrMode.IndirectY),
	("LDY",   AddrMode.ZeroPageX),
	("LDA",   AddrMode.ZeroPageX),
	("LDX",   AddrMode.ZeroPageY),
	("LAX",   AddrMode.ZeroPageY),
	("CLV",   AddrMode.Implied),
	("LDA",   AddrMode.AbsoluteY),
	("TSX",   AddrMode.Implied),
	("LAS",   AddrMode.AbsoluteY),
	("LDY",   AddrMode.AbsoluteX),
	("LDA",   AddrMode.AbsoluteX),
	("LDX",   AddrMode.AbsoluteY),
	("LAX",   AddrMode.AbsoluteY),
	("CPY",   AddrMode.Immediate),
	("CMP",   AddrMode.IndirectX),
	("NOOP",  AddrMode.Immediate),
	("DCP",   AddrMode.IndirectX),
	("CPY",   AddrMode.ZeroPage),
	("CMP",   AddrMode.ZeroPage),
	("DEC",   AddrMode.ZeroPage),
	("DCP",   AddrMode.ZeroPage),
	("INY",   AddrMode.Implied),
	("CMP",   AddrMode.Immediate),
	("DEX",   AddrMode.Implied),
	("SBX",   AddrMode.Immediate),
	("CPY",   AddrMode.Absolute),
	("CMP",   AddrMode.Absolute),
	("DEC",   AddrMode.Absolute),
	("DCP",   AddrMode.Absolute),
	("BNE",   AddrMode.Relative),
	("CMP",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("DCP",   AddrMode.IndirectY),
	("NOOP",  AddrMode.ZeroPageX),
	("CMP",   AddrMode.ZeroPageX),
	("DEC",   AddrMode.ZeroPageX),
	("DCP",   AddrMode.ZeroPageX),
	("CLD",   AddrMode.Implied),
	("CMP",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.Implied),
	("DCP",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.AbsoluteX),
	("CMP",   AddrMode.AbsoluteX),
	("DEC",   AddrMode.AbsoluteX),
	("DCP",   AddrMode.AbsoluteX),
	("CPX",   AddrMode.Immediate),
	("SBC",   AddrMode.IndirectX),
	("NOOP",  AddrMode.Immediate),
	("ISB",   AddrMode.IndirectX),
	("CPX",   AddrMode.ZeroPage),
	("SBC",   AddrMode.ZeroPage),
	("INC",   AddrMode.ZeroPage),
	("ISB",   AddrMode.ZeroPage),
	("INX",   AddrMode.Implied),
	("SBC",   AddrMode.Immediate),
	("NOP",   AddrMode.Implied),
	("USBC",  AddrMode.Immediate),
	("CPX",   AddrMode.Absolute),
	("SBC",   AddrMode.Absolute),
	("INC",   AddrMode.Absolute),
	("ISB",   AddrMode.Absolute),
	("BEQ",   AddrMode.Relative),
	("SBC",   AddrMode.IndirectY),
	("JAM",   AddrMode.Implied),
	("ISB",   AddrMode.IndirectY),
	("NOOP",  AddrMode.ZeroPageX),
	("SBC",   AddrMode.ZeroPageX),
	("INC",   AddrMode.ZeroPageX),
	("ISB",   AddrMode.ZeroPageX),
	("SED",   AddrMode.Implied),
	("SBC",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.Implied),
	("ISB",   AddrMode.AbsoluteY),
	("NOOP",  AddrMode.AbsoluteX),
	("SBC",   AddrMode.AbsoluteX),
	("INC",   AddrMode.AbsoluteX),
	("ISB",   AddrMode.Absolute)
	]

def read_word(b, i):
	return b[i]+b[i+1]*256

try:
	f = open("5000-8fff.bin", "rb")
	b = f.read()

	mm = menumonics[b[0x1b16]];
	print(mm[0]+" "+modes[mm[1]][1].format(b[0x1b17]))

finally:
	f.close()
