#!/usr/bin/env python3

from enum import Enum, unique, auto

@unique
class AddressingMode(Enum):
	Implied = auto()
	Accumulator = auto()
	Immediate = auto()
	ZeroPage = auto()
	ZeroPageX = auto()
	ZeroPageY = auto()
	Absolute = auto()
	AbsoluteX = auto()
	AbsoluteY = auto()
	AbsIndirect = auto()
	IndirectX = auto()
	IndirectY = auto()
	Relative = auto()

menumonics_modes = [
	("BRK",   AddressingMode.Implied),
	("ORA",   AddressingMode.IndirectX),
	("JAM",   AddressingMode.Implied),
	("SLO",   AddressingMode.IndirectX),
	("NOOP",  AddressingMode.ZeroPage),
	("ORA",   AddressingMode.ZeroPage),
	("ASL",   AddressingMode.ZeroPage),
	("SLO",   AddressingMode.ZeroPage),
	("PHP",   AddressingMode.Implied),
	("ORA",   AddressingMode.Immediate),
	("ASL",   AddressingMode.Accumulator),
	("ANC",   AddressingMode.Immediate),
	("NOOP",  AddressingMode.Absolute),
	("ORA",   AddressingMode.Absolute),
	("ASL",   AddressingMode.Absolute),
	("SLO",   AddressingMode.Absolute),
	("BPL",   AddressingMode.Relative),
	("ORA",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("SLO",   AddressingMode.IndirectY),
	("NOOP",  AddressingMode.ZeroPageX),
	("ORA",   AddressingMode.ZeroPageX),
	("ASL",   AddressingMode.ZeroPageX),
	("SLO",   AddressingMode.ZeroPageX),
	("CLC",   AddressingMode.Implied),
	("ORA",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.Implied),
	("SLO",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.AbsoluteX),
	("ORA",   AddressingMode.AbsoluteX),
	("ASL",   AddressingMode.AbsoluteX),
	("SLO",   AddressingMode.AbsoluteX),
	("JSR",   AddressingMode.Absolute),
	("AND",   AddressingMode.IndirectX),
	("JAM",   AddressingMode.Implied),
	("RLA",   AddressingMode.IndirectX),
	("BIT",   AddressingMode.ZeroPage),
	("AND",   AddressingMode.ZeroPage),
	("ROL",   AddressingMode.ZeroPage),
	("RLA",   AddressingMode.ZeroPage),
	("PLP",   AddressingMode.Implied),
	("AND",   AddressingMode.Immediate),
	("ROL",   AddressingMode.Accumulator),
	("ANC",   AddressingMode.Immediate),
	("BIT",   AddressingMode.Absolute),
	("AND",   AddressingMode.Absolute),
	("ROL",   AddressingMode.Absolute),
	("RLA",   AddressingMode.Absolute),
	("BMI",   AddressingMode.Relative),
	("AND",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("RLA",   AddressingMode.IndirectY),
	("NOOP",  AddressingMode.ZeroPageX),
	("AND",   AddressingMode.ZeroPageX),
	("ROL",   AddressingMode.ZeroPageX),
	("RLA",   AddressingMode.ZeroPageX),
	("SEC",   AddressingMode.Implied),
	("AND",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.Implied),
	("RLA",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.AbsoluteX),
	("AND",   AddressingMode.AbsoluteX),
	("ROL",   AddressingMode.AbsoluteX),
	("RLA",   AddressingMode.AbsoluteX),
	("RTI",   AddressingMode.Implied),
	("EOR",   AddressingMode.IndirectX),
	("JAM",   AddressingMode.Implied),
	("SRE",   AddressingMode.IndirectX),
	("NOOP",  AddressingMode.ZeroPage),
	("EOR",   AddressingMode.ZeroPage),
	("LSR",   AddressingMode.ZeroPage),
	("SRE",   AddressingMode.ZeroPage),
	("PHA",   AddressingMode.Implied),
	("EOR",   AddressingMode.Immediate),
	("LSR",   AddressingMode.Accumulator),
	("ASR",   AddressingMode.Immediate),
	("JMP",   AddressingMode.Absolute),
	("EOR",   AddressingMode.Absolute),
	("LSR",   AddressingMode.Absolute),
	("SRE",   AddressingMode.Absolute),
	("BVC",   AddressingMode.Relative),
	("EOR",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("SRE",   AddressingMode.IndirectY),
	("NOOP",  AddressingMode.ZeroPageX),
	("EOR",   AddressingMode.ZeroPageX),
	("LSR",   AddressingMode.ZeroPageX),
	("SRE",   AddressingMode.ZeroPageX),
	("CLI",   AddressingMode.Implied),
	("EOR",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.Implied),
	("SRE",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.AbsoluteX),
	("EOR",   AddressingMode.AbsoluteX),
	("LSR",   AddressingMode.AbsoluteX),
	("SRE",   AddressingMode.AbsoluteX),
	("RTS",   AddressingMode.Implied),
	("ADC",   AddressingMode.IndirectX),
	("JAM",   AddressingMode.Implied),
	("RRA",   AddressingMode.IndirectX),
	("NOOP",  AddressingMode.ZeroPage),
	("ADC",   AddressingMode.ZeroPage),
	("ROR",   AddressingMode.ZeroPage),
	("RRA",   AddressingMode.ZeroPage),
	("PLA",   AddressingMode.Implied),
	("ADC",   AddressingMode.Immediate),
	("ROR",   AddressingMode.Accumulator),
	("ARR",   AddressingMode.Immediate),
	("JMP",   AddressingMode.AbsIndirect),
	("ADC",   AddressingMode.Absolute),
	("ROR",   AddressingMode.Absolute),
	("RRA",   AddressingMode.Absolute),
	("BVS",   AddressingMode.Relative),
	("ADC",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("RRA",   AddressingMode.IndirectY),
	("NOOP",  AddressingMode.ZeroPageX),
	("ADC",   AddressingMode.ZeroPageX),
	("ROR",   AddressingMode.ZeroPageX),
	("RRA",   AddressingMode.ZeroPageX),
	("SEI",   AddressingMode.Implied),
	("ADC",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.Implied),
	("RRA",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.AbsoluteX),
	("ADC",   AddressingMode.AbsoluteX),
	("ROR",   AddressingMode.AbsoluteX),
	("RRA",   AddressingMode.AbsoluteX),
	("NOOP",  AddressingMode.Immediate),
	("STA",   AddressingMode.IndirectX),
	("NOOP",  AddressingMode.Immediate),
	("SAX",   AddressingMode.IndirectX),
	("STY",   AddressingMode.ZeroPage),
	("STA",   AddressingMode.ZeroPage),
	("STX",   AddressingMode.ZeroPage),
	("SAX",   AddressingMode.ZeroPage),
	("DEY",   AddressingMode.Implied),
	("NOOP",  AddressingMode.Immediate),
	("TXA",   AddressingMode.Implied),
	("ANE",   AddressingMode.Immediate),
	("STY",   AddressingMode.Absolute),
	("STA",   AddressingMode.Absolute),
	("STX",   AddressingMode.Absolute),
	("SAX",   AddressingMode.Absolute),
	("BCC",   AddressingMode.Relative),
	("STA",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("SHA",   AddressingMode.IndirectY),
	("STY",   AddressingMode.ZeroPageX),
	("STA",   AddressingMode.ZeroPageX),
	("STX",   AddressingMode.ZeroPageY),
	("SAX",   AddressingMode.ZeroPageY),
	("TYA",   AddressingMode.Implied),
	("STA",   AddressingMode.AbsoluteY),
	("TXS",   AddressingMode.Implied),
	("SHS",   AddressingMode.AbsoluteY),
	("SHY",   AddressingMode.AbsoluteX),
	("STA",   AddressingMode.AbsoluteX),
	("SHX",   AddressingMode.AbsoluteY),
	("SHA",   AddressingMode.AbsoluteY),
	("LDY",   AddressingMode.Immediate),
	("LDA",   AddressingMode.IndirectX),
	("LDX",   AddressingMode.Immediate),
	("LAX",   AddressingMode.IndirectX),
	("LDY",   AddressingMode.ZeroPage),
	("LDA",   AddressingMode.ZeroPage),
	("LDX",   AddressingMode.ZeroPage),
	("LAX",   AddressingMode.ZeroPage),
	("TAY",   AddressingMode.Implied),
	("LDA",   AddressingMode.Immediate),
	("TAX",   AddressingMode.Implied),
	("LXA",   AddressingMode.Immediate),
	("LDY",   AddressingMode.Absolute),
	("LDA",   AddressingMode.Absolute),
	("LDX",   AddressingMode.Absolute),
	("LAX",   AddressingMode.Absolute),
	("BCS",   AddressingMode.Relative),
	("LDA",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("LAX",   AddressingMode.IndirectY),
	("LDY",   AddressingMode.ZeroPageX),
	("LDA",   AddressingMode.ZeroPageX),
	("LDX",   AddressingMode.ZeroPageY),
	("LAX",   AddressingMode.ZeroPageY),
	("CLV",   AddressingMode.Implied),
	("LDA",   AddressingMode.AbsoluteY),
	("TSX",   AddressingMode.Implied),
	("LAS",   AddressingMode.AbsoluteY),
	("LDY",   AddressingMode.AbsoluteX),
	("LDA",   AddressingMode.AbsoluteX),
	("LDX",   AddressingMode.AbsoluteY),
	("LAX",   AddressingMode.AbsoluteY),
	("CPY",   AddressingMode.Immediate),
	("CMP",   AddressingMode.IndirectX),
	("NOOP",  AddressingMode.Immediate),
	("DCP",   AddressingMode.IndirectX),
	("CPY",   AddressingMode.ZeroPage),
	("CMP",   AddressingMode.ZeroPage),
	("DEC",   AddressingMode.ZeroPage),
	("DCP",   AddressingMode.ZeroPage),
	("INY",   AddressingMode.Implied),
	("CMP",   AddressingMode.Immediate),
	("DEX",   AddressingMode.Implied),
	("SBX",   AddressingMode.Immediate),
	("CPY",   AddressingMode.Absolute),
	("CMP",   AddressingMode.Absolute),
	("DEC",   AddressingMode.Absolute),
	("DCP",   AddressingMode.Absolute),
	("BNE",   AddressingMode.Relative),
	("CMP",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("DCP",   AddressingMode.IndirectY),
	("NOOP",  AddressingMode.ZeroPageX),
	("CMP",   AddressingMode.ZeroPageX),
	("DEC",   AddressingMode.ZeroPageX),
	("DCP",   AddressingMode.ZeroPageX),
	("CLD",   AddressingMode.Implied),
	("CMP",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.Implied),
	("DCP",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.AbsoluteX),
	("CMP",   AddressingMode.AbsoluteX),
	("DEC",   AddressingMode.AbsoluteX),
	("DCP",   AddressingMode.AbsoluteX),
	("CPX",   AddressingMode.Immediate),
	("SBC",   AddressingMode.IndirectX),
	("NOOP",  AddressingMode.Immediate),
	("ISB",   AddressingMode.IndirectX),
	("CPX",   AddressingMode.ZeroPage),
	("SBC",   AddressingMode.ZeroPage),
	("INC",   AddressingMode.ZeroPage),
	("ISB",   AddressingMode.ZeroPage),
	("INX",   AddressingMode.Implied),
	("SBC",   AddressingMode.Immediate),
	("NOP",   AddressingMode.Implied),
	("USBC",  AddressingMode.Immediate),
	("CPX",   AddressingMode.Absolute),
	("SBC",   AddressingMode.Absolute),
	("INC",   AddressingMode.Absolute),
	("ISB",   AddressingMode.Absolute),
	("BEQ",   AddressingMode.Relative),
	("SBC",   AddressingMode.IndirectY),
	("JAM",   AddressingMode.Implied),
	("ISB",   AddressingMode.IndirectY),
	("NOOP",  AddressingMode.ZeroPageX),
	("SBC",   AddressingMode.ZeroPageX),
	("INC",   AddressingMode.ZeroPageX),
	("ISB",   AddressingMode.ZeroPageX),
	("SED",   AddressingMode.Implied),
	("SBC",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.Implied),
	("ISB",   AddressingMode.AbsoluteY),
	("NOOP",  AddressingMode.AbsoluteX),
	("SBC",   AddressingMode.AbsoluteX),
	("INC",   AddressingMode.AbsoluteX),
	("ISB",   AddressingMode.Absolute)
]

def read_word(b, i):
	return b[i]+b[i+1]*256

try:
	f = open("5000-8fff.bin", "rb")
	b = f.read()
	print([hex(v) for v in b])
	print(hex(read_word(b, 0xfca)))
finally:
	f.close()
